name: Node CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPad Air (3rd generation)']
        xcode: ['/Applications/Xcode_11.1.app/Contents/Developer']
        node-version: [12.x]

    steps:
      # Show env
      - name: Show macOS version
        run: sw_vers
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Show devices
        run: xcrun instruments -s devices
      - name: Show simctl list
        run: xcrun simctl list
      - name: Launch simulator
        run: |
          xcrun simctl boot D368CE6D-AE01-456F-A75E-B5432501A263
          open '/Applications/Xcode_11.1.app/Contents/Developer/Applications/Simulator.app/'
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          defaults write com.apple.Safari IncludeDevelopMenu YES
          defaults write com.apple.Safari AllowRemoteAutomation 1
          sudo safaridriver --enable
          safaridriver -p 0 &
          npm install
          npm build
          npm run test
        env:
          destination: ${{ matrix.destination }}
