name: Node CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPad Air (3rd generation)']
        xcode: ['/Applications/Xcode_11.1.app/Contents/Developer']
        node-version: [12.x]

    steps:
      # Show env
      - name: Show macOS version
        run: sw_vers
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Show devices
        run: xcrun instruments -s devices
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run test
        env:
          destination: ${{ matrix.destination }}
